server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventariodb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: inventario-service

logging:
  level:
    org.springframework.web: DEBUG