server:
  port: 8081

spring:
  application:
    name: productos-service

  datasource:
    url: jdbc:postgresql://localhost:5432/productosdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO